### ISSUE TITLE
Code block syntax highlighting not working properly

### ISSUE THREAD

**Issue by EIFY** [iclr-blogposts/2024#53]
The [relevant section](https://iclr-blogposts.github.io/2024/blog/distill-example/#code-blocks) of the Sample Blog Post is now rendered like this on my Mac, both in Chrome and Safari:

<img width="716" alt="Screenshot 2023-11-26 at 3 09 42 PM" src="https://github.com/iclr-blogposts/2024/assets/2584418/fc6ac715-2815-41a8-af34-d4af251e44af">

Which doesn't seem correct. If I reload the page, for a split second it seems to show the correct C++ syntax highlights, so I suspect there is some unintended style sheet overwrite going on. The same happens when I work on my own blog post with python syntax highlighting.

**Comment by fabianp** [comment]
The same code from al-folio looks much nicer: https://alshedivat.github.io/al-folio/blog/2015/code/

**Comment by EIFY** [comment]
FYI 2023 Blogposts are also affected, e.g. you can see flashes of correct python syntax highlighting by reloading the intro of [Decay No More](https://iclr-blogposts.github.io/2023/blog/2023/adamw/#introduction). Hopefully this helps `git bisect` the issue...

**Comment by fabianp** [comment]
I think this is now fixed in https://github.com/iclr-blogposts/2024/commit/af5cd61f6be081e8d407235017425e9fa4ccf29e
<img width="748" alt="image" src="https://github.com/iclr-blogposts/2024/assets/277639/dd025e20-0acd-4df0-bb62-32179086a472">


The issue was that there's a JS library that was interfering with Jekyll's highlight system. 

I'll close this for now but please reopen if the issue persists
