### ISSUE TITLE
Obtaining URL for Blog Post Pull Request?

### ISSUE THREAD

**Issue by RylanSchaeffer** [iclr-blogposts/2024#55]
The [submission instructions state](https://iclr-blogposts.github.io/2024/submitting/#submitting-your-blog-post):

<blockquote>
Open a pull request against the main branch of the [2024 repo](https://github.com/iclr-blogposts/2024). Fill in the checklist provided in the PR template. The title of your pull request should be exactly the name of your markdown/html file.

    i.e. _posts/2024-05-07-[SUBMISSION NAME].md would require a PR name 2024-05-07-[SUBMISSION NAME]

(TBD) Your post will automatically run two pipelines: one to verify that you have not modified any other file in the repo, and another that will create a unique URL for your contributed blog post.

    Verify that everything looks correct in the given URL.
    If the pipelines failed, check if it was because of improper formatting (i.e. you modified restricted files). If this is the case, fix the issues. If the issue persist, please ping one of the repo admins.
</blockquote>

[I opened a PR here](https://github.com/iclr-blogposts/2024/pull/54) but I've been unable to find out where our submission URL is. I don't see a comment on the PR and I haven't received anything by email.

Could someone please clarify?

**Comment by RylanSchaeffer** [comment]
In this example PR

https://github.com/iclr-blogposts/2024/pull/48

GitHub actions added a comment:

<blockquote>
👋 Thanks for your submission! We have successfully built your website and we will push it shortly to the URL https://d2jud02ci9yv69.cloudfront.net/2024-05-07-works-48/blog/works/ !
</blockquote>

I didn't receive anything like that for my PR. Might I have done something wrong?

**Comment by RylanSchaeffer** [comment]
I see a message: `filter-files / Detect what files changed (pull_request) Skipped`

Could this be the culprit?

**Comment by fabianp** [comment]
Thanks for the report @RylanSchaeffer . I'm looking into it

**Comment by fabianp** [comment]
Hi @RylanSchaeffer , and apologies for this hiccup. There should indeed be no modifications to other files other than your post. I see at least modifications to .gitignore, _layouts/distill.html (which I BTW just incorporated in the main repo, and _posts/2024-05-07-distill-example.md and _posts/2024-05-07-distill-example2.html , which should be left intact.

It's still odd that you didn't get an error message. We have a check that should have warned you of these issues (@Velythyl I suspect the issue was that the runs were only run if the PR had an assigned "Submission" tag, I changed it here https://github.com/iclr-blogposts/2024/commit/7507ec1737563d45138b5c5feb95b1b1dca70b10 . Is there a reason why we should only run after we've set up the "Submission" tag?).

In any case, please update your pull request @RylanSchaeffer with the modifications mentioned above and let us know if it works

**Comment by Velythyl** [comment]
We were skipping PRs without the Submission tag to prevent our pipeline to run when we make our own hotfix/fixes/improvements/etc PRs. But I think we originally did that because the pipeline would auto-close failed PRs. Now that we don't autoclose, it's safe to run on all PRs, even without the Submission tag.

**Comment by fabianp** [comment]
@RylanSchaeffer : it seems the issue has been fixed. I'll close this issue.

BTW, I just submitted a small fix that should fix some color issues I saw in your post with the dark theme (some math was appearing black). If you merge from master those problems should hopefully go away
